### ISSUE TITLE
Revisar la organización de las carpetas

### ISSUE THREAD

**Issue by aguirre739** [AdrianMilo/Projecto404#1]
La carpeta no está organizada correctamente, hay una carpeta con una subcarpeta con el proyecto completo.

![image](https://user-images.githubusercontent.com/43866443/200439781-4081a93f-293d-4031-ba20-fcbaefb08d80.png)

**Comment by AdrianMilo** [comment]
Muchas gracias Pame por todas las observacions. Nos sirven muchísimo para el proyecto que estamos realizando actualmente. Las tendremos presente y las corregiremos.
